DS6/config/routes.rb
Rails.application.routes.draw do
  resources :notes
  resources :exams
  resources :enrollments
  resources :subjects
  resources :administrators
  resources :students
  resources :professors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'professors#index'

  get "/app/assets/apks/flutter.apk" => "descarga#descargar"
  get "/app/assets/images/*route", to:"notes#descargar"
  
  namespace :api, defaults: { format: 'json' }  do
    namespace :v1 do
      resources :notes
      resources :exams
      resources :enrollments
      resources :subjects
      resources :administrators
      resources :students
      resources :professors
    end
  end
  get "/api/v1/notes/images/*route" => "notes#descargar"
end

DS6/app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :subject
  belongs_to :student
end

DS6/app/controllers/api/v1/enrollments_controller.rb
module Api
  module V1
class EnrollmentsController < ApplicationController
  skip_before_action :verify_authenticity_token

  # GET /enrollments or /enrollments.json
  def index
    render json: Enrollment.all, status: :ok
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
    @enrollments = Enrollment.find_by(id: params[:id])
    if (@enrollments!=nil)
      render json: @enrollments, status: :ok
    else  
      render json: :nothing, status: :not_found
    end
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    if @enrollment.save
      render json: @enrollment, status: :created
    else
      render json: @enrollment.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    @enrollment = Enrollment.find(params[:id])

    if @enrollment.update(enrollment_params)
      render json: @enrollment, status: :ok
    else
      render json: @enrollment.errors, status: :unprocessable_entity
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment = Enrollment.find_by(id: params[:id])
    if @enrollment.destroy
      render json: :nothing, status: :ok
    else
      render json: :nothing, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:subject_id, :student_id)
    end
end
end
end

DS6/app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]

  # GET /enrollments or /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: "Enrollment was successfully created." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:subject_id, :student_id)
    end
end

DS6/app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

DS6/app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment) do |form| %>
  <% if enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
        <% enrollment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject_id %>
    <%= form.collection_select :subject_id, Subject.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.collection_select :student_id, Student.all, :id, :fullname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

DS6/app/views/enrollments/edit.html.erb
<h1>Editing Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

DS6/app/views/enrollments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrollments</h1>

<table id="tabla">
  <thead>
    <tr>
      <th>Subject</th>
      <th>Student</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.subject.name %></td>
        <td><%= enrollment.student.name + " " + enrollment.student.surname %></td>
        <td><%= link_to 'Show', enrollment %></td>
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_enrollment_path %>

DS6/app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Back', enrollments_path %>

DS6/app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @enrollment.subject_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @enrollment.student_id %>
</p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>