DS6/config/routes.rb
Rails.application.routes.draw do
  resources :notes
  resources :exams
  resources :enrollments
  resources :subjects
  resources :administrators
  resources :students
  resources :professors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'professors#index'

  get "/app/assets/apks/flutter.apk" => "descarga#descargar"
  get "/app/assets/images/*route", to:"notes#descargar"
  
  namespace :api, defaults: { format: 'json' }  do
    namespace :v1 do
      resources :notes
      resources :exams
      resources :enrollments
      resources :subjects
      resources :administrators
      resources :students
      resources :professors
    end
  end
  get "/api/v1/notes/images/*route" => "notes#descargar"
end

DS6/app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :subject
end

DS6/app/controllers/api/v1/exams_controller.rb
module Api
  module V1
class ExamsController < ApplicationController
  skip_before_action :verify_authenticity_token

  # GET /exams or /exams.json
  def index
    render json: Exam.all, status: :ok
  end

  # GET /exams/1 or /exams/1.json
  def show
    @exam = Exam.find_by(id: params[:id])
    if (@exam!=nil)
      render json: @exam, status: :ok
    else  
      render json: :nothing, status: :not_found
    end
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams or /exams.json
  def create
    @exam = Exam.new(exam_params)

    if @exam.save
      render json: @exam, status: :created
    else
      render json: @exam.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /exams/1 or /exams/1.json
  def update
    @exam = Exam.find(params[:id])

    if @exam.update(exam_params)
      render json: @exam, status: :ok
    else
      render json: @exam.errors, status: :unprocessable_entity
    end
  end

  # DELETE /exams/1 or /exams/1.json
  def destroy
    @exam = Exam.find_by(id: params[:id])
    if @exam.destroy
      render json: :nothing, status: :ok
    else
      render json: :nothing, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exam_params
      params.require(:exam).permit(:name, :date, :subject_id)
    end
end
end
end

DS6/app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: %i[ show edit update destroy ]

  # GET /exams or /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1 or /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams or /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: "Exam was successfully created." }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1 or /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: "Exam was successfully updated." }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1 or /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: "Exam was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exam_params
      params.require(:exam).permit(:name, :date, :subject_id)
    end
end

DS6/app/helpers/exams_helper.rb
module ExamsHelper
end

DS6/app/views/exams/_form.html.erb
<%= form_with(model: exam) do |form| %>
  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
        <% exam.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :subject_id %>
    <%= form.collection_select :subject_id, Subject.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

DS6/app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

DS6/app/views/exams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exams</h1>

<table id="tabla">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Subject</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.name %></td>
        <td><%= exam.date %></td>
        <td><%= exam.subject.name %></td>
        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exam', new_exam_path %>

DS6/app/views/exams/new.html.erb
<h1>New Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Back', exams_path %>

DS6/app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exam.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @exam.date %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @exam.subject_id %>
</p>

<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>